### ISSUE TITLE
HTTP-OPTION Requests result in Error

### ISSUE THREAD

**Issue by bastianleirpo** [Fraunhofer-AISEC/omejdn-server#18]
I encountered some CORS problems when using a front end. Everytime the browser sends OPTIONS request, OMEJDN throws an Exception: `ERROR NoMethodError: undefined method `upcase' for nil:NilClass` which might come from sinatra.

I fixed these problems by adding
`return if request.env['REQUEST_METHOD'] == 'OPTIONS'`
after
`before '/api/v1/user*' do`
and
`before '/api/v1/config/*' do`

Could you verify these issues?

**Comment by oxisto** [comment]
I think this was fixed in #23?

**Comment by bellebaum** [comment]
It should work for now, but we should revisit this in the future. You can close this issue if you like
