### ISSUE TITLE
API and admin access scope handling should be improved

### ISSUE THREAD

**Issue by schanzen** [Fraunhofer-AISEC/omejdn-server#4]
Currently, the scopes `omejdn:api` and `omejdn:admin` can be requested and if the attributes with such keys are configured the respective access tokens can be used to access the (admin) API.

A better approach would be to have scopes such as:

  - `omejdn:read`
  - `omejdn:write`
  - `omejdn:admin`

Those scopes then map to an attribute `omejdn` which can have the values `read`, `write`, `admin`
.

**Comment by bellebaum** [comment]
I am closing this issue for now due to above commit addressing this issue
