### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by aetxeberriasqs** [Fraunhofer-AISEC/omejdn-server#40]
There are two ways to install the DAPS, one with the oficial git at https://github.com/International-Data-Spaces-Association/omejdn-daps where the installation is made with bundle and the other at https://github.com/Fraunhofer-AISEC/omejdn-server that is made with docker.

In the second link, it states how to install it using docker, yet in the first page, this option is no written.  The two methods are not well connected and it leads to misinterpretation. The documentation, and the part on how to do it with dockers, should be included in the oficial documentation, and there steps to reach that point clearly stated and well separated. 

It should appear all the steps that are neccesary to reach the point of the installation with docker

**Comment by bellebaum** [comment]
Thanks for your issue,
you have reached the repository for Omejdn, a general purpose OAuth 2.0 and OIDC Authorization Server.
The term DAPS does have no meaning in this repository. It is specific to the International Data Spaces context.
