### ISSUE TITLE
How to request an access token?

### ISSUE THREAD

**Issue by sebplorenz** [Fraunhofer-AISEC/omejdn-server#51]
The part "Requesting an access token", which was very helpful, has been removed from the main readme with #49. Where can this information be found now?

**Comment by schanzen** [comment]
Here: https://datatracker.ietf.org/doc/html/rfc7523#section-2.2

**Comment by bellebaum** [comment]
I tried to keep the README somewhat short and precise.
Once I have the necessary time, I can write down some detailed documentation.

Until then, the link above should help.
The method has not changed however, hence the old README versions should still work for the time being:
https://github.com/Fraunhofer-AISEC/omejdn-server/tree/v1.4.2#requesting-an-access-token-rfc7523

**Comment by sebplorenz** [comment]
Hi,
yes, the example at https://github.com/Fraunhofer-AISEC/omejdn-server/tree/v1.4.2#requesting-an-access-token-rfc7523 was really helpful for me when configuring my own connector implementation as a DAPS client using the Micronaut Security Framework. It should be preserved in the docs.
