### ISSUE TITLE
Bug in KEYS_LOAD_ALL event of DefaultKeysDB

### ISSUE THREAD

**Issue by spetrac-nicos-ag** [Fraunhofer-AISEC/omejdn-server#66]
While searching the sourcecode for another issue, I found a bug:
I guess the `KEYS_LOAD_ALL` event should load all keys of the `target_type`. Then the 2 occurences of `"keys/omejdn/#{f}"` should maybe better be `"#{KEYS_DIR}/#{target_type}/#{f}"` to load the key from the correct directory.

https://github.com/Fraunhofer-AISEC/omejdn-server/blob/c767a7a11e2776f1cbdb53f21ae74edd739ed138/lib/keys.rb#L121-L132

**Comment by bellebaum** [comment]
Well spotted :)
Will be fixed later today
